name: Java CI with Gradle

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: prod
      RDS_HOST: ${{ secrets.RDS_HOST }}
      RDS_PORT: ${{ secrets.RDS_PORT }}
      RDS_NAME: ${{ secrets.RDS_NAME }}
      RDS_USER: ${{ secrets.RDS_USER }}
      RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      SECURITY_USER_NAME: ${{ secrets.SECURITY_USER_NAME }}
      SECURITY_USER_PASSWORD: ${{ secrets.SECURITY_USER_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
      JWT_REFRESH_TOKEN_EXPIRATION: ${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION }}
      JWT_EMAIL_VERIFICATION_EXPIRATION: ${{ secrets.JWT_EMAIL_VERIFICATION_EXPIRATION }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      S3_NAME: ${{ secrets.S3_NAME }}
      S3_KEY: ${{ secrets.S3_KEY }}
      S3_SECRET: ${{ secrets.S3_SECRET }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          host port: ${{ secrets.RDS_PORT }}
          mysql database: ${{ secrets.RDS_NAME }}
          mysql user: ${{ secrets.RDS_USER }}
          mysql password: ${{ secrets.RDS_PASSWORD }}
          character set server: "utf8mb4"
          collation server: "utf8mb4_unicode_ci"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test with Gradle
        run: ./gradlew build test
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
